# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis_proto/redis_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='redis_proto/redis_config.proto',
  package='tfx.examples.custom_components.redis_example_gen',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eredis_proto/redis_config.proto\x12\x30tfx.examples.custom_components.redis_example_gen\"\xa9\x01\n\x0fRedisConnConfig\x12\x0e\n\x04host\x18\x01 \x01(\tH\x00\x12\x0e\n\x04port\x18\x02 \x01(\rH\x01\x12\x0c\n\x02\x64\x62\x18\x03 \x01(\rH\x02\x12\x12\n\x08username\x18\x04 \x01(\tH\x03\x12\x12\n\x08password\x18\x05 \x01(\tH\x04\x42\n\n\x08opt_hostB\n\n\x08opt_portB\x08\n\x06opt_dbB\x0e\n\x0copt_usernameB\x0e\n\x0copt_passwordb\x06proto3'
)




_REDISCONNCONFIG = _descriptor.Descriptor(
  name='RedisConnConfig',
  full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='db', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.db', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='opt_host', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.opt_host',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_port', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.opt_port',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_db', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.opt_db',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_username', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.opt_username',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='opt_password', full_name='tfx.examples.custom_components.redis_example_gen.RedisConnConfig.opt_password',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=85,
  serialized_end=254,
)

_REDISCONNCONFIG.oneofs_by_name['opt_host'].fields.append(
  _REDISCONNCONFIG.fields_by_name['host'])
_REDISCONNCONFIG.fields_by_name['host'].containing_oneof = _REDISCONNCONFIG.oneofs_by_name['opt_host']
_REDISCONNCONFIG.oneofs_by_name['opt_port'].fields.append(
  _REDISCONNCONFIG.fields_by_name['port'])
_REDISCONNCONFIG.fields_by_name['port'].containing_oneof = _REDISCONNCONFIG.oneofs_by_name['opt_port']
_REDISCONNCONFIG.oneofs_by_name['opt_db'].fields.append(
  _REDISCONNCONFIG.fields_by_name['db'])
_REDISCONNCONFIG.fields_by_name['db'].containing_oneof = _REDISCONNCONFIG.oneofs_by_name['opt_db']
_REDISCONNCONFIG.oneofs_by_name['opt_username'].fields.append(
  _REDISCONNCONFIG.fields_by_name['username'])
_REDISCONNCONFIG.fields_by_name['username'].containing_oneof = _REDISCONNCONFIG.oneofs_by_name['opt_username']
_REDISCONNCONFIG.oneofs_by_name['opt_password'].fields.append(
  _REDISCONNCONFIG.fields_by_name['password'])
_REDISCONNCONFIG.fields_by_name['password'].containing_oneof = _REDISCONNCONFIG.oneofs_by_name['opt_password']
DESCRIPTOR.message_types_by_name['RedisConnConfig'] = _REDISCONNCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedisConnConfig = _reflection.GeneratedProtocolMessageType('RedisConnConfig', (_message.Message,), {
  'DESCRIPTOR' : _REDISCONNCONFIG,
  '__module__' : 'redis_proto.redis_config_pb2'
  # @@protoc_insertion_point(class_scope:tfx.examples.custom_components.redis_example_gen.RedisConnConfig)
  })
_sym_db.RegisterMessage(RedisConnConfig)


# @@protoc_insertion_point(module_scope)
