# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis_proto/redis_hash_query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='redis_proto/redis_hash_query.proto',
  package='tfx.examples.custom_components.redis_example_gen',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"redis_proto/redis_hash_query.proto\x12\x30tfx.examples.custom_components.redis_example_gen\"\x84\x01\n\x0eRedisHashQuery\x12\x18\n\x10hash_key_pattern\x18\x01 \x01(\t\x12X\n\x06schema\x18\x02 \x03(\x0b\x32H.tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema\"\xd2\x01\n\x16redis_hash_pair_schema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x66\n\x04type\x18\x02 \x01(\x0e\x32X.tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema.hash_field_type\"B\n\x0fhash_field_type\x12\x0b\n\x07unkonwn\x10\x00\x12\x0b\n\x07integer\x10\x01\x12\t\n\x05\x66loat\x10\x02\x12\n\n\x06string\x10\x03\x62\x06proto3'
)



_REDIS_HASH_PAIR_SCHEMA_HASH_FIELD_TYPE = _descriptor.EnumDescriptor(
  name='hash_field_type',
  full_name='tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema.hash_field_type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='unkonwn', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='integer', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='float', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='string', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=368,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_REDIS_HASH_PAIR_SCHEMA_HASH_FIELD_TYPE)


_REDISHASHQUERY = _descriptor.Descriptor(
  name='RedisHashQuery',
  full_name='tfx.examples.custom_components.redis_example_gen.RedisHashQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_key_pattern', full_name='tfx.examples.custom_components.redis_example_gen.RedisHashQuery.hash_key_pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema', full_name='tfx.examples.custom_components.redis_example_gen.RedisHashQuery.schema', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=221,
)


_REDIS_HASH_PAIR_SCHEMA = _descriptor.Descriptor(
  name='redis_hash_pair_schema',
  full_name='tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REDIS_HASH_PAIR_SCHEMA_HASH_FIELD_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=434,
)

_REDISHASHQUERY.fields_by_name['schema'].message_type = _REDIS_HASH_PAIR_SCHEMA
_REDIS_HASH_PAIR_SCHEMA.fields_by_name['type'].enum_type = _REDIS_HASH_PAIR_SCHEMA_HASH_FIELD_TYPE
_REDIS_HASH_PAIR_SCHEMA_HASH_FIELD_TYPE.containing_type = _REDIS_HASH_PAIR_SCHEMA
DESCRIPTOR.message_types_by_name['RedisHashQuery'] = _REDISHASHQUERY
DESCRIPTOR.message_types_by_name['redis_hash_pair_schema'] = _REDIS_HASH_PAIR_SCHEMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedisHashQuery = _reflection.GeneratedProtocolMessageType('RedisHashQuery', (_message.Message,), {
  'DESCRIPTOR' : _REDISHASHQUERY,
  '__module__' : 'redis_proto.redis_hash_query_pb2'
  # @@protoc_insertion_point(class_scope:tfx.examples.custom_components.redis_example_gen.RedisHashQuery)
  })
_sym_db.RegisterMessage(RedisHashQuery)

redis_hash_pair_schema = _reflection.GeneratedProtocolMessageType('redis_hash_pair_schema', (_message.Message,), {
  'DESCRIPTOR' : _REDIS_HASH_PAIR_SCHEMA,
  '__module__' : 'redis_proto.redis_hash_query_pb2'
  # @@protoc_insertion_point(class_scope:tfx.examples.custom_components.redis_example_gen.redis_hash_pair_schema)
  })
_sym_db.RegisterMessage(redis_hash_pair_schema)


# @@protoc_insertion_point(module_scope)
